name: Lint code

on:
  push:
  pull_request:
    branches-ignore: [ master ]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608
    - name: Set up Python 3.9
      uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b
      with:
        python-version: 3.9
    - name: Run pre-commit
      uses: pre-commit/action@646c83fcd040023954eafda54b4db0192ce70507
