name: Lint code

on:
  push:
  pull_request:
    branches-ignore: [ master ]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
    - name: Set up Python 3.9
      uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3
      with:
        python-version: 3.9
    - name: Run pre-commit
      uses: pre-commit/action@646c83fcd040023954eafda54b4db0192ce70507
